// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Week12Day4Demo.Data.Models
{
    public partial class Booking
    {
        [Key]
        public int Id { get; set; }
        public int HotelRefId { get; set; }
        [Column(TypeName = "date")]
        public DateTime BookingStartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime BookingEndDate { get; set; }
        public int CustomerRefId { get; set; }

        [ForeignKey(nameof(CustomerRefId))]
        [InverseProperty(nameof(Customer.Bookings))]
        public virtual Customer CustomerRef { get; set; }
        [ForeignKey(nameof(HotelRefId))]
        [InverseProperty(nameof(Hotel.Bookings))]
        public virtual Hotel HotelRef { get; set; }
    }
}