// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Week12Day4Demo.Data.Models
{
    public partial class Hotel
    {
        public Hotel()
        {
            Bookings = new HashSet<Booking>();
        }

        [Key]
        public int? Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(1500)]
        public string Address { get; set; }
        [StringLength(500)]
        public string PhotoUrl { get; set; }
        public double? CostPerNight { get; set; }
        public double? MyProfitMargin { get; set; }

        [InverseProperty(nameof(Booking.HotelRef))]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}